apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
